// Generated by CoffeeScript 1.7.1
(function() {
  var accord, adapters;

  accord = require('accord');

  adapters = {};

  module.exports = function(adapter, customPath, method, args, cb) {
    var _ref;
    if (!(adapter in adapters)) {
      adapters[adapter] = accord.load(adapter, customPath);
    }
    return (_ref = adapters[adapter])[method].apply(_ref, args).then(function(res) {
      return cb(null, JSON.stringify(res));
    }, function(err) {
      return cb(err);
    });
  };

}).call(this);
