// Generated by CoffeeScript 1.7.1
(function() {
  var JASON, accord, adapters;

  accord = require('accord');

  JASON = require('JASON');

  adapters = {};

  module.exports = function(adapter, method, args, cb) {
    var _ref;
    if (!(adapter in adapters)) {
      adapters[adapter] = accord.load(adapter);
    }
    return (_ref = adapters[adapter])[method].apply(_ref, args).then(function(res) {
      return cb(null, JASON.stringify(res));
    }, function(err) {
      return cb(err);
    });
  };

}).call(this);
